# Generated by Django 4.2.5 on 2023-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searched_product',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='product_price_history',
            name='product_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searched_product',
            name='product_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
